<?php

/**
 * Implements hook_theme().
 */
 function material_theme($existing, $type, $theme, $path) {
  // Custom template to render weather data on a page.
  return [
    'weather_rendered_data' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];

}

/**
 * Implements hook_page_attachments().
 */
function material_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'material/weather';
}